name: Create Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        type: string
      release-title:
        required: false
        type: string
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      release-title:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: false

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-release:
    runs-on: [ 'ubuntu-24.04' ]

    steps:
    - uses: actions/checkout@v6.0.1
    - uses: de-vri-es/setup-git-credentials@v2.1.2
      with:
        credentials: ${{ secrets.GH_TOKEN }}
    - uses: milosz-barylowicz/cpp-projects-github-actions/python3-upgrade@main
      with:
        python3-version: '15'
        operating-system: 'ubuntu-24.04'

    - name: python3-venv-creation
      run: |
        python3.15 -m venv venv && \
        source venv/bin/activate
    - name: creating-release
      if: inputs.release-title == ''
      run: |
        set -e
        python ./.github/workflows/scripts/create_release.py --release_version ${{ inputs.release-version }}

    - name: creating-release-with-title
      if: inputs.release-title != ''
      run: |
        set -e
        python ./.github/workflows/scripts/create_release.py --release_version ${{ inputs.release-version }} --release_title ${{ inputs.release-title }}
